import { useState } from "react";
import axios from "axios";
import toast from "react-hot-toast";
import { useNavigate, Link } from "react-router-dom";
import { GoogleLogin } from "@react-oauth/google";

const API = "https://humorous-fulfillment-production-1f5e.up.railway.app/api";
const field = "w-full rounded-xl border border-slate-300 px-3 py-3 outline-none focus:border-blue-500";

export default function EmployerAuth({ login = false }) {
  const navigate = useNavigate();
  const [form, setForm] = useState({ fullName:"", email:"", mobile:"", companyName:"", website:"", companyType:"Private company", industry:"", companySize:"1-10", city:"", state:"", password:"" });
  const update = (e) => setForm({ ...form, [e.target.name]: e.target.value });
  const submit = async (e) => { e.preventDefault(); try { const { data } = await axios.post(`${API}/employers/${login ? "login" : "register"}`, login ? { email:form.email, password:form.password } : form); localStorage.setItem("token", data.token); localStorage.setItem("role", "employer"); localStorage.setItem("userId", data.userId); toast.success(login ? "Welcome back" : "Employer account created"); navigate("/employer/dashboard"); } catch (err) { toast.error(err.response?.data?.error || "Please try again"); } };
  const googleSignIn = async (credentialResponse) => { try { if (!login && (!form.fullName || !form.companyName || !form.mobile || !form.city || !form.state)) return toast.error("Complete your company details before continuing with Google."); const { data } = await axios.post(`${API}/google-login`, { credential: credentialResponse.credential, accountType: "employer", employerProfile: form }); localStorage.setItem("token", data.token); localStorage.setItem("role", "employer"); localStorage.setItem("userId", data.userId); localStorage.setItem("username", data.username); localStorage.setItem("email", data.email); toast.success("Employer account ready"); navigate("/employer/dashboard"); } catch (err) { toast.error(err.response?.data?.error || "Google sign-in failed. Please try again."); } };
  return <main className="min-h-screen bg-slate-100 p-5"><form onSubmit={submit} className="mx-auto max-w-3xl rounded-3xl bg-white p-7 shadow-xl md:p-10"><Link to="/employers" className="font-semibold text-blue-700">← For employers</Link><h1 className="mt-5 text-3xl font-black">{login ? "Employer Login" : "Create your employer account"}</h1><p className="mt-2 text-slate-600">{login ? "Access your jobs and hiring activity." : "Your vacancies will be checked before they go live."}</p><div className="mt-7 grid gap-4 md:grid-cols-2">{!login && <><input required name="fullName" onChange={update} placeholder="Full name *" className={field}/><input required name="mobile" onChange={update} placeholder="Mobile number *" className={field}/><input required name="companyName" onChange={update} placeholder="Company name *" className={field}/><input name="website" onChange={update} placeholder="Company website (https://...)" className={field}/><select name="companyType" onChange={update} className={field}><option>Private company</option><option>Startup</option><option>Recruitment agency</option><option>Non-profit</option></select><input name="industry" onChange={update} placeholder="Industry" className={field}/><select name="companySize" onChange={update} className={field}><option>1-10</option><option>11-50</option><option>51-200</option><option>201-500</option><option>500+</option></select><input required name="city" onChange={update} placeholder="City *" className={field}/><input required name="state" onChange={update} placeholder="State *" className={field}/></>}<input required type="email" name="email" onChange={update} placeholder="Work email *" className={field}/><input required minLength="8" type="password" name="password" onChange={update} placeholder="Password (8+ characters) *" className={field}/></div><button className="mt-7 w-full rounded-xl bg-blue-600 px-5 py-3 font-bold text-white hover:bg-blue-700">{login ? "Login" : "Create account & post a job"}</button><div className="my-5 flex items-center gap-3 text-xs font-medium uppercase tracking-wide text-slate-400"><span className="h-px flex-1 bg-slate-200"/>or continue with<span className="h-px flex-1 bg-slate-200"/></div><div className="flex justify-center"><GoogleLogin onSuccess={googleSignIn} onError={() => toast.error("Google sign-in failed. Please try again.")} text={login ? "signin_with" : "signup_with"} width="300" /></div><p className="mt-5 text-center text-sm">{login ? "New employer?" : "Already have an account?"} <Link className="font-bold text-blue-700" to={login ? "/employer/register" : "/employer/login"}>{login ? "Register" : "Employer login"}</Link></p></form></main>;
}
