import { Link, useLocation } from "react-router-dom";

const supportEmail = "care@marketlence.com";
const supportPhone = "+91 99968 10408";
const updated = "28 August 2026";

const Section = ({ title, children }) => <section className="mt-7"><h2 className="text-xl font-black text-slate-900">{title}</h2><div className="mt-2 space-y-3 leading-7 text-slate-700">{children}</div></section>;

export default function LegalPolicies() {
  const path = useLocation().pathname;
  const policy = path.includes("privacy") ? "privacy" : path.includes("refund") ? "refund" : path.includes("contact") ? "contact" : "terms";
  const title = policy === "privacy" ? "Privacy Policy" : policy === "refund" ? "Refund & Cancellation Policy" : policy === "contact" ? "Contact Us" : "Terms & Conditions";

  return <main className="min-h-screen bg-slate-100 px-4 py-8 md:py-12"><article className="mx-auto max-w-4xl rounded-3xl bg-white p-6 shadow-xl md:p-10"><Link to="/" className="font-bold text-blue-700 hover:text-blue-900">← Back to MarketLence Jobs</Link><p className="mt-7 text-sm font-black tracking-[0.18em] text-blue-700">MARKETLENCE JOBS</p><h1 className="mt-2 text-3xl font-black text-slate-950 md:text-4xl">{title}</h1><p className="mt-3 text-sm text-slate-500">Last updated: {updated}</p>
    {policy === "privacy" && <><Section title="Introduction"><p>MarketLence Jobs respects your privacy. This policy explains how we collect, use, store and protect information when you use jobs.marketlence.com, including candidate, employer and job-alert services.</p></Section><Section title="Information we collect"><p>We may collect account details such as name, email address and profile information; job application information such as resumes and answers; employer company and job-posting information; and technical information needed to operate, secure and improve the platform.</p></Section><Section title="How we use information"><p>We use information to provide job-search, application, employer and customer-support services; send requested job alerts; prevent fraud and misuse; and meet legal obligations. We do not sell personal information.</p></Section><Section title="Sharing and retention"><p>Candidate application information is shared with the employer for the job selected by the candidate. We may use trusted service providers for hosting, email, payments and analytics where required to operate the platform. We retain information only for as long as necessary for the purposes described or as required by law.</p></Section><Section title="Your choices"><p>You may request access, correction or deletion of your account information by emailing <a className="font-bold text-blue-700" href={`mailto:${supportEmail}`}>{supportEmail}</a>. Some records may need to be retained for legal, security or transaction purposes.</p></Section></>}
    {policy === "terms" && <><Section title="Acceptance of these terms"><p>By accessing or using MarketLence Jobs, you agree to these Terms & Conditions. If you do not agree, please do not use the platform.</p></Section><Section title="Platform role"><p>MarketLence Jobs provides a platform for discovering jobs, submitting applications and publishing employer vacancies. We do not guarantee an interview, selection, employment offer, job accuracy or an employer’s response.</p></Section><Section title="User responsibilities"><p>Users must provide accurate information, use only their own account, protect their login credentials and not submit unlawful, misleading, abusive or infringing content. Employers are responsible for the accuracy, legality and authenticity of their job posts and application processes.</p></Section><Section title="Paid featured listings"><p>Featured listing services provide enhanced visibility for an employer’s job post. Visibility is not a guarantee of applications, hiring or any particular result. A featured listing is subject to approval and the selected duration.</p></Section><Section title="Suspension and changes"><p>We may review, remove, pause or refuse content or accounts that violate these terms, applicable law or platform safety standards. We may update the platform or these terms from time to time.</p></Section></>}
    {policy === "refund" && <><Section title="Cancellation"><p>An employer may request cancellation of a featured-listing order before the promotion is activated by contacting us at <a className="font-bold text-blue-700" href={`mailto:${supportEmail}`}>{supportEmail}</a>. Please include the registered email, job title and payment reference.</p></Section><Section title="Refunds"><p>Refund requests are reviewed on a case-by-case basis. If a paid featured promotion has not been activated due to an error on our side, we will review the request for a suitable resolution. Once a featured promotion has been activated and delivered, it is generally non-refundable because the visibility service has started.</p></Section><Section title="Duplicate or failed payments"><p>If you are charged more than once for the same order, or a payment is completed but the service is not activated, contact us promptly with your payment reference. Verified duplicate charges will be refunded to the original payment method where applicable.</p></Section><Section title="Processing time"><p>Where a refund is approved, it is initiated to the original payment method. The time for it to appear depends on the bank or payment provider.</p></Section></>}
    {policy === "contact" && <><Section title="Customer support"><p>For account assistance, featured listing questions, payment concerns, cancellation requests, refunds, privacy requests or platform feedback, email us at <a className="font-bold text-blue-700" href={`mailto:${supportEmail}`}>{supportEmail}</a> or call <a className="font-bold text-blue-700" href="tel:+919996810408">{supportPhone}</a>.</p><p>Please include your registered email address and, where applicable, your job title or payment reference so our team can assist you efficiently.</p></Section><Section title="About the platform"><p>MarketLence Jobs is an online employment platform that connects candidates with job opportunities and enables employers to publish and manage job listings.</p></Section></>}
    <div className="mt-10 border-t pt-6 text-sm text-slate-500"><p>Related information: <Link className="font-semibold text-blue-700" to="/privacy-policy">Privacy Policy</Link> · <Link className="font-semibold text-blue-700" to="/terms-and-conditions">Terms & Conditions</Link> · <Link className="font-semibold text-blue-700" to="/refund-cancellation-policy">Refund & Cancellation</Link> · <Link className="font-semibold text-blue-700" to="/contact-us">Contact Us</Link></p></div>
  </article></main>;
}
