import { Link, useLocation } from "react-router-dom";

const supportEmail = "care@marketlence.com";
const supportPhone = "+91 99968 10408";
const legalName = "Bikramjeet Singh";
const registeredAddress = "426 Derapindoria, Kaithal Road, Assandh, Karnal, Haryana 132039, India";
const updated = "29 August 2026";

const Section = ({ title, children }) => <section className="mt-7"><h2 className="text-xl font-black text-slate-900">{title}</h2><div className="mt-2 space-y-3 leading-7 text-slate-700">{children}</div></section>;
const ContactLine = () => <p><b>Operator:</b> {legalName}<br/><b>Address:</b> {registeredAddress}<br/><b>Email:</b> <a className="font-bold text-blue-700" href={`mailto:${supportEmail}`}>{supportEmail}</a><br/><b>Mobile:</b> <a className="font-bold text-blue-700" href="tel:+919996810408">{supportPhone}</a></p>;

export default function LegalPolicies() {
  const path = useLocation().pathname;
  const policy = path.includes("privacy") ? "privacy" : path.includes("return-refund") || path.includes("refund-cancellation") ? "refund" : path.includes("cancellation") ? "cancellation" : path.includes("shipping") ? "shipping" : path.includes("about") ? "about" : path.includes("services") ? "services" : path.includes("contact") ? "contact" : "terms";
  const title = { privacy: "Privacy Policy", refund: "Return & Refund Policy", cancellation: "Cancellation Policy", shipping: "Shipping / Digital Delivery Policy", about: "About Us", services: "Services & Pricing", contact: "Contact Us", terms: "Terms & Conditions" }[policy];

  return <main className="min-h-screen bg-slate-100 px-4 py-8 md:py-12"><article className="mx-auto max-w-4xl rounded-3xl bg-white p-6 shadow-xl md:p-10"><Link to="/" className="font-bold text-blue-700 hover:text-blue-900">← Back to MarketLence Jobs</Link><p className="mt-7 text-sm font-black tracking-[0.18em] text-blue-700">MARKETLENCE JOBS</p><h1 className="mt-2 text-3xl font-black text-slate-950 md:text-4xl">{title}</h1><p className="mt-3 text-sm text-slate-500">Last updated: {updated}</p>

    {policy === "privacy" && <><Section title="Introduction"><p>This website is operated by {legalName}. MarketLence Jobs respects your privacy and explains here how information is collected, used and protected when you use jobs.marketlence.com.</p></Section><Section title="Information we collect"><p>We may collect account details, profile information, resumes, job application answers, employer company and job-posting information, and technical information needed to operate and secure the platform.</p></Section><Section title="How we use information"><p>We use information to provide job search, application, employer, payment and support services; send requested job alerts; prevent fraud; and meet legal obligations. We do not sell personal information.</p></Section><Section title="Sharing and retention"><p>Candidate application information is shared with the employer for the job selected by the candidate. We may use trusted providers for hosting, email, payments and analytics only where required to operate the platform.</p></Section><Section title="Your choices"><p>You may request access, correction or deletion of your information by emailing <a className="font-bold text-blue-700" href={`mailto:${supportEmail}`}>{supportEmail}</a>.</p></Section></>}

    {policy === "terms" && <><Section title="Acceptance"><p>By using MarketLence Jobs, you agree to these Terms & Conditions. This website is operated by {legalName}.</p></Section><Section title="Platform role"><p>MarketLence Jobs helps candidates discover jobs and enables employers to publish vacancies. We do not guarantee an interview, selection, employment offer, job accuracy or employer response.</p></Section><Section title="User responsibilities"><p>Users must provide accurate information, use only their own account and not submit unlawful, misleading, abusive or infringing content. Employers are responsible for the accuracy and legality of their job posts.</p></Section><Section title="Paid services"><p>Featured listing services provide enhanced visibility for an employer’s job post. Visibility does not guarantee applications or hiring and is subject to approval and the selected duration.</p></Section></>}

    {policy === "refund" && <><Section title="Eligibility and duration"><p>Refund requests for a featured job listing must be raised within <b>7 calendar days</b> of successful payment. A refund may be considered if the paid promotion was not activated because of a technical or service error on our side.</p></Section><Section title="Non-refundable service"><p>Once a featured promotion has been activated and the visibility service has started, the service is generally non-refundable because the digital service has been delivered.</p></Section><Section title="Refund mode and timeline"><p>Approved refunds are processed only to the <b>original payment method</b>. We initiate approved refunds within <b>5 business days</b>; the bank or payment provider may take a further <b>5–7 business days</b> to reflect the amount.</p></Section><Section title="Duplicate payments"><p>Verified duplicate charges for the same order are refunded to the original payment method after review. Email your payment reference, job title and registered email to <a className="font-bold text-blue-700" href={`mailto:${supportEmail}`}>{supportEmail}</a>.</p></Section></>}

    {policy === "cancellation" && <><Section title="Cancellation duration"><p>You may request cancellation of a featured-listing order within <b>24 hours</b> of payment, provided the promotion has not already been activated.</p></Section><Section title="How to cancel"><p>Email <a className="font-bold text-blue-700" href={`mailto:${supportEmail}`}>{supportEmail}</a> with your registered email address, job title and payment reference. We will acknowledge the request and review it within <b>2 business days</b>.</p></Section><Section title="After activation"><p>After the featured promotion is activated, it cannot normally be cancelled because the digital visibility service has begun. Any eligible refund is handled under the Return & Refund Policy.</p></Section></>}

    {policy === "shipping" && <><Section title="Digital service only"><p>MarketLence Jobs provides digital services only. No physical product is shipped and no physical delivery charges apply.</p></Section><Section title="Delivery duration"><p>After successful payment, a featured job listing is normally activated within <b>1 business day</b>, subject to job-content review and approval. The selected featured duration begins after activation.</p></Section><Section title="Delivery confirmation"><p>Activation is confirmed through the employer dashboard and/or the registered email address. If a paid service is not activated within the stated timeframe, contact <a className="font-bold text-blue-700" href={`mailto:${supportEmail}`}>{supportEmail}</a> with your payment reference.</p></Section></>}

    {policy === "services" && <><Section title="Featured Job Listing"><p>Employers can purchase enhanced visibility for an approved job listing on MarketLence Jobs. The service places the job with premium featured presentation and priority visibility on the platform for the selected period.</p><div className="mt-4 overflow-hidden rounded-2xl border border-violet-200"><div className="grid grid-cols-2 bg-violet-700 p-3 text-sm font-black text-white"><span>Service</span><span>Price (INR)</span></div><div className="grid grid-cols-2 border-t p-4 text-slate-700"><span><b>Featured job listing – 7 days</b></span><span><b>₹299</b></span></div><div className="grid grid-cols-2 border-t p-4 text-slate-700"><span><b>Featured job listing – 29 days</b></span><span><b>₹499</b></span></div></div><p className="mt-4">Prices are in Indian Rupees (INR). The service is digital and is subject to successful payment, job approval and the policies shown on this website.</p></Section></>}

    {policy === "about" && <><Section title="About MarketLence Jobs"><p>MarketLence Jobs is an online employment platform that helps candidates discover job opportunities and helps employers publish, promote and manage job listings. Our aim is to make job discovery and employer outreach simpler, clearer and more accessible.</p></Section><Section title="Our services"><p>We provide job search and job alerts for candidates, employer job-posting tools, application management tools and optional paid featured visibility for employer job listings.</p></Section><Section title="Website operator"><ContactLine /></Section></>}

    {policy === "contact" && <><Section title="Customer support"><p>For account assistance, payment concerns, cancellation requests, refund requests, privacy requests or platform feedback, contact us using the details below.</p><ContactLine /><p>Please include your registered email address and, where relevant, the job title and payment reference so we can assist you efficiently.</p></Section></>}

    <div className="mt-10 border-t pt-6 text-sm text-slate-500"><p className="font-semibold text-slate-700">Related information</p><p className="mt-2 flex flex-wrap gap-x-3 gap-y-1"><Link className="font-semibold text-blue-700" to="/about-us">About Us</Link><Link className="font-semibold text-blue-700" to="/privacy-policy">Privacy Policy</Link><Link className="font-semibold text-blue-700" to="/terms-and-conditions">Terms & Conditions</Link><Link className="font-semibold text-blue-700" to="/return-refund-policy">Return & Refund</Link><Link className="font-semibold text-blue-700" to="/cancellation-policy">Cancellation</Link><Link className="font-semibold text-blue-700" to="/shipping-policy">Shipping / Delivery</Link><Link className="font-semibold text-blue-700" to="/services-pricing">Services & Pricing</Link><Link className="font-semibold text-blue-700" to="/contact-us">Contact Us</Link></p></div>
  </article></main>;
}
