import { createElement, useEffect, useState } from "react";
import axios from "axios";
import toast from "react-hot-toast";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, Ban, CalendarClock, CheckCircle2, Clock3, Download, Headphones, Phone, PhoneCall, PhoneMissed, Plus, Settings2, UsersRound } from "lucide-react";

const API = "https://humorous-fulfillment-production-1f5e.up.railway.app/api/telephony";
const auth = () => ({ headers: { Authorization: `Bearer ${localStorage.getItem("token")}` } });
const field = "w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm outline-none transition focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100";
const blankClient = { name: "", organization: "", phone: "", assignedEmployeeId: "", assignedTeam: "", campaignId: "", consentStatus: "unknown", consentBasis: "", consentSource: "" };
const blankResult = { disposition: "", notes: "", followUp: { dueAt: "", reason: "", priority: "Medium" } };

function duration(seconds = 0) { const value = Number(seconds) || 0; return `${Math.floor(value / 60)}m ${value % 60}s`; }

export default function TelephonyCRM() {
  const navigate = useNavigate();
  const [data, setData] = useState(null), [busy, setBusy] = useState(""), [tab, setTab] = useState("dialler");
  const [client, setClient] = useState(blankClient), [result, setResult] = useState(blankResult), [selectedCall, setSelectedCall] = useState(null);
  const [settings, setSettings] = useState(null);
  const load = async () => { try { const response = await axios.get(`${API}/overview`, auth()); setData(response.data); setSettings(response.data.settings); } catch (error) { toast.error(error.response?.data?.error || "Could not load business calling."); navigate("/admin/people"); } };
  useEffect(() => {
    let active = true;
    axios.get(`${API}/overview`, auth()).then((response) => { if (active) { setData(response.data); setSettings(response.data.settings); } }).catch((error) => { if (active) { toast.error(error.response?.data?.error || "Could not load business calling."); navigate("/admin/people"); } });
    return () => { active = false; };
  }, [navigate]);
  const capabilities = new Set(data?.capabilities || []);
  const saveClient = async (event) => { event.preventDefault(); setBusy("client"); try { await axios.post(`${API}/clients`, client, auth()); setClient(blankClient); toast.success("Client added and assigned"); load(); } catch (error) { toast.error(error.response?.data?.error || "Could not add client."); } finally { setBusy(""); } };
  const startCall = async (clientId) => { if (!window.confirm("Call this assigned client through the official MarketLence business number?")) return; setBusy(`call-${clientId}`); try { await axios.post(`${API}/calls`, { clientId }, auth()); toast.success("Call requested. Your phone will ring first."); load(); } catch (error) { toast.error(error.response?.data?.error || "The call could not be started."); } finally { setBusy(""); } };
  const saveResult = async (event) => { event.preventDefault(); setBusy("result"); try { await axios.patch(`${API}/calls/${selectedCall.id}/disposition`, { ...result, followUp: result.followUp.dueAt ? result.followUp : undefined }, auth()); toast.success("Call result saved"); setSelectedCall(null); setResult(blankResult); load(); } catch (error) { toast.error(error.response?.data?.error || "Could not save the call result."); } finally { setBusy(""); } };
  const completeFollowUp = async (id) => { try { await axios.patch(`${API}/followups/${id}`, { status: "Completed" }, auth()); load(); } catch (error) { toast.error(error.response?.data?.error || "Could not complete follow-up."); } };
  const saveSettings = async (event) => { event.preventDefault(); setBusy("settings"); try { await axios.patch(`${API}/settings`, { provider: settings.provider, callingEnabled: settings.calling_enabled, businessNumber: settings.business_number, recordingEnabled: settings.recording_enabled, recordingRetentionDays: settings.recording_retention_days, callingStart: settings.calling_start, callingEnd: settings.calling_end, timezone: settings.timezone, defaultCountryCode: settings.default_country_code, callDurationLimitSeconds: settings.call_duration_limit_seconds, noteRequiredDispositions: settings.note_required_dispositions }, auth()); toast.success("Calling settings saved"); load(); } catch (error) { toast.error(error.response?.data?.error || "Could not save settings."); } finally { setBusy(""); } };
  const testConnection = async () => { try { const { data: response } = await axios.post(`${API}/settings/test`, {}, auth()); toast[response.ok ? "success" : "error"](response.message || response.error); } catch (error) { toast.error(error.response?.data?.error || "Provider connection is not ready."); } };
  const exportCsv = async () => { try { const response = await axios.get(`${API}/export.csv`, { ...auth(), responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = "marketlence-calls.csv"; link.click(); URL.revokeObjectURL(url); } catch { toast.error("You do not have permission to export this report."); } };
  if (!data) return <main className="grid min-h-screen place-items-center bg-[#f6f7ff]"><p className="font-bold text-slate-500">Loading business calling…</p></main>;
  const metricCards = [["Calls today", data.metrics.calls_today, PhoneCall, "text-indigo-600 bg-indigo-50"], ["Connected", data.metrics.connected_calls, CheckCircle2, "text-emerald-600 bg-emerald-50"], ["Unanswered", data.metrics.unanswered_calls, PhoneMissed, "text-rose-600 bg-rose-50"], ["Talk time", duration(data.metrics.total_talk_seconds), Clock3, "text-cyan-600 bg-cyan-50"], ["Interested", data.metrics.interested_clients, UsersRound, "text-amber-600 bg-amber-50"], ["Conversions", data.metrics.conversions, CheckCircle2, "text-violet-600 bg-violet-50"]];

  return <main className="min-h-screen bg-[#f6f7ff] p-4 text-slate-800 md:p-8"><div className="mx-auto max-w-7xl">
    <button onClick={() => navigate("/admin/people")} className="inline-flex items-center gap-2 text-sm font-bold text-indigo-700"><ArrowLeft size={16}/> Back to People CRM</button>
    <section className="relative mt-4 overflow-hidden rounded-[2rem] bg-slate-950 p-7 text-white shadow-2xl md:p-10"><div className="absolute -right-20 -top-20 h-72 w-72 rounded-full bg-cyan-500/20 blur-3xl"/><div className="relative flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-black tracking-[.22em] text-cyan-300">MARKETLENCE BUSINESS CALLING</p><h1 className="mt-3 text-3xl font-black md:text-5xl">Client conversations, accountable.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Assigned calls, outcomes, callbacks and reporting—using the official business number.</p></div><div className={`rounded-2xl px-4 py-3 text-sm font-black ${data.settings.providerConfigured ? "bg-emerald-400/15 text-emerald-200" : "bg-amber-400/15 text-amber-200"}`}>{data.settings.providerConfigured ? `Ready · ${data.settings.provider}` : "Business calling is not configured"}</div></div></section>
    {!data.settings.providerConfigured && <div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900"><b>Calls remain disabled.</b> An administrator must configure server credentials, approve the business number and legal notices, then enable calling. No test call will be simulated.</div>}
    <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{metricCards.map(([label,value,Icon,colors])=><article key={label} className="rounded-2xl bg-white p-4 shadow-sm"><span className={`grid h-9 w-9 place-items-center rounded-xl ${colors}`}>{createElement(Icon,{size:18})}</span><p className="mt-4 text-xs font-bold text-slate-500">{label}</p><b className="mt-1 block text-2xl font-black">{value || 0}</b></article>)}</section>
    <nav className="mt-6 flex flex-wrap gap-2 rounded-2xl bg-white p-2 shadow-sm">{[["dialler","Dialler",Phone],["calls","Call history",PhoneCall],["followups","Follow-ups",CalendarClock],...(capabilities.has("manage_telephony_settings")?[["settings","Settings",Settings2]]:[])].map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`inline-flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-black ${tab===id?"bg-slate-950 text-white":"text-slate-500 hover:bg-slate-100"}`}>{createElement(Icon,{size:16})}{label}</button>)}{capabilities.has("export_reports")&&<button onClick={exportCsv} className="ml-auto inline-flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-black text-indigo-700"><Download size={16}/> Export CSV</button>}</nav>
    {tab==="dialler"&&<section className="mt-6 grid gap-6 xl:grid-cols-[.7fr_1.3fr]">{capabilities.has("view_all_calls")&&<form onSubmit={saveClient} className="rounded-3xl bg-white p-6 shadow-sm"><p className="text-xs font-black tracking-widest text-indigo-600">ASSIGNED CLIENT</p><h2 className="mt-2 text-2xl font-black">Add client</h2><div className="mt-5 grid gap-3"><input required value={client.name} onChange={e=>setClient({...client,name:e.target.value})} placeholder="Client name *" className={field}/><input value={client.organization} onChange={e=>setClient({...client,organization:e.target.value})} placeholder="Organization" className={field}/><input required value={client.phone} onChange={e=>setClient({...client,phone:e.target.value})} placeholder="Phone number *" className={field}/><select required value={client.assignedEmployeeId} onChange={e=>setClient({...client,assignedEmployeeId:e.target.value})} className={field}><option value="">Assign employee *</option>{(data.employees||[]).map(item=><option key={item.id} value={item.id}>{item.full_name}</option>)}</select><input value={client.assignedTeam} onChange={e=>setClient({...client,assignedTeam:e.target.value})} placeholder="Team / department" className={field}/><select value={client.consentStatus} onChange={e=>setClient({...client,consentStatus:e.target.value})} className={field}><option value="unknown">Contact consent not recorded</option><option value="granted">Contact consent recorded</option><option value="declined">Contact declined</option></select><textarea value={client.consentBasis} onChange={e=>setClient({...client,consentBasis:e.target.value})} placeholder="Consent purpose and basis (requires compliance-approved wording)" className={`${field} min-h-20`}/><button disabled={busy==="client"} className="rounded-xl bg-indigo-600 py-3 font-black text-white"><Plus className="mr-2 inline" size={16}/> Add assigned client</button></div></form>}
      <section className="overflow-hidden rounded-3xl bg-white shadow-sm"><div className="border-b p-6"><h2 className="text-2xl font-black">Assigned clients</h2><p className="mt-1 text-sm text-slate-500">Numbers remain masked; the provider bridges both parties.</p></div><div className="divide-y">{data.clients.map(item=><article key={item.id} className="flex flex-wrap items-center gap-4 p-5"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-indigo-50 font-black text-indigo-700">{item.name.slice(0,2).toUpperCase()}</span><div className="min-w-48 flex-1"><b>{item.name}</b><p className="mt-1 text-xs text-slate-500">{item.organization||"Independent client"} · {item.phoneMasked}</p><p className="mt-1 text-xs text-slate-400">{item.assigned_employee_name||"Unassigned"} · {item.assigned_team||"No team"}</p></div>{item.do_not_call?<span className="inline-flex items-center gap-1 rounded-full bg-rose-100 px-3 py-1 text-xs font-black text-rose-700"><Ban size={13}/> Do not call</span>:<button onClick={()=>startCall(item.id)} disabled={!data.settings.providerConfigured||Boolean(busy)} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-3 text-sm font-black text-white disabled:bg-slate-300"><Phone size={16}/>{busy===`call-${item.id}`?"Connecting…":"Call client"}</button>}</article>)}{!data.clients.length&&<p className="p-12 text-center text-slate-400">No clients are assigned yet.</p>}</div></section></section>}
    {tab==="calls"&&<section className="mt-6 overflow-hidden rounded-3xl bg-white shadow-sm"><div className="border-b p-6"><h2 className="text-2xl font-black">Call history</h2><p className="text-sm text-slate-500">Provider-confirmed status only. Completed calls require a result.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Client","Employee","Started","Status","Duration","Result","Recording",""].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{data.calls.map(call=><tr key={call.id} className="border-t"><td className="px-4 py-4 font-bold">{call.client_name}<small className="block text-slate-400">{call.phoneMasked}</small></td><td className="px-4">{call.employee_name}</td><td className="px-4">{call.started_at?new Date(call.started_at).toLocaleString():"Queued"}</td><td className="px-4 font-bold capitalize">{call.status}</td><td className="px-4">{duration(call.duration_seconds)}</td><td className="px-4">{call.disposition||<span className="text-amber-700">Required</span>}</td><td className="px-4">{call.recording_available?<span className="inline-flex items-center gap-1 text-indigo-700"><Headphones size={15}/> Available</span>:"—"}</td><td className="px-4">{!call.disposition&&["completed","busy","no-answer","failed","cancelled"].includes(call.status)&&<button onClick={()=>setSelectedCall(call)} className="font-black text-indigo-700">Select call result</button>}</td></tr>)}</tbody></table></div></section>}
    {tab==="followups"&&<section className="mt-6 grid gap-4 md:grid-cols-2">{data.followups.map(item=><article key={item.id} className={`rounded-3xl bg-white p-5 shadow-sm ${item.overdue?"ring-2 ring-rose-200":""}`}><div className="flex justify-between gap-3"><div><b>{item.client_name}</b><p className="mt-1 text-sm text-slate-500">{item.reason}</p></div><span className={`h-fit rounded-full px-3 py-1 text-xs font-black ${item.overdue?"bg-rose-100 text-rose-700":"bg-indigo-50 text-indigo-700"}`}>{item.overdue?"Overdue":item.status}</span></div><p className="mt-4 text-xs font-bold text-slate-500">Due {new Date(item.due_at).toLocaleString()} · {item.priority}</p>{item.status!=="Completed"&&<button onClick={()=>completeFollowUp(item.id)} className="mt-4 rounded-xl bg-slate-950 px-4 py-2 text-sm font-black text-white">Mark completed</button>}</article>)}{!data.followups.length&&<p className="rounded-3xl bg-white p-12 text-center text-slate-400">No callbacks scheduled.</p>}</section>}
    {tab==="settings"&&settings&&<form onSubmit={saveSettings} className="mt-6 rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-2xl font-black">Business calling settings</h2><p className="mt-2 text-sm text-amber-700">Legal wording, recording notices and retention require compliance approval. Secrets remain server-side.</p><div className="mt-6 grid gap-4 md:grid-cols-2"><select value={settings.provider} onChange={e=>setSettings({...settings,provider:e.target.value})} className={field}><option value="disabled">Disabled</option><option value="exotel">Exotel</option></select><input value={settings.business_number||""} onChange={e=>setSettings({...settings,business_number:e.target.value})} placeholder="Official business number" className={field}/><input type="time" value={String(settings.calling_start).slice(0,5)} onChange={e=>setSettings({...settings,calling_start:e.target.value})} className={field}/><input type="time" value={String(settings.calling_end).slice(0,5)} onChange={e=>setSettings({...settings,calling_end:e.target.value})} className={field}/><input value={settings.timezone} onChange={e=>setSettings({...settings,timezone:e.target.value})} placeholder="Timezone" className={field}/><input type="number" value={settings.recording_retention_days} onChange={e=>setSettings({...settings,recording_retention_days:e.target.value})} placeholder="Recording retention days" className={field}/></div><div className="mt-5 flex flex-wrap gap-5"><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={settings.calling_enabled} onChange={e=>setSettings({...settings,calling_enabled:e.target.checked})}/> Calling enabled</label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={settings.recording_enabled} onChange={e=>setSettings({...settings,recording_enabled:e.target.checked})}/> Recording enabled after approval</label></div><div className="mt-6 flex gap-3"><button disabled={busy==="settings"} className="rounded-xl bg-indigo-600 px-5 py-3 font-black text-white">Save settings</button><button type="button" onClick={testConnection} className="rounded-xl border border-indigo-200 px-5 py-3 font-black text-indigo-700">Test connection</button></div></form>}
    {selectedCall&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><form onSubmit={saveResult} className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><h2 className="text-2xl font-black">Select call result</h2><p className="mt-1 text-sm text-slate-500">{selectedCall.client_name} · {selectedCall.phoneMasked}</p><select required value={result.disposition} onChange={e=>setResult({...result,disposition:e.target.value})} className={`${field} mt-5`}><option value="">Choose result *</option>{data.dispositions.map(value=><option key={value}>{value}</option>)}</select><textarea value={result.notes} onChange={e=>setResult({...result,notes:e.target.value})} placeholder="Call notes" className={`${field} mt-3 min-h-24`}/><h3 className="mt-5 font-black">Schedule follow-up</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><input type="datetime-local" value={result.followUp.dueAt} onChange={e=>setResult({...result,followUp:{...result.followUp,dueAt:e.target.value}})} className={field}/><select value={result.followUp.priority} onChange={e=>setResult({...result,followUp:{...result.followUp,priority:e.target.value}})} className={field}>{["Low","Medium","High","Urgent"].map(x=><option key={x}>{x}</option>)}</select></div><input value={result.followUp.reason} onChange={e=>setResult({...result,followUp:{...result.followUp,reason:e.target.value}})} placeholder="Follow-up reason" className={`${field} mt-3`}/><div className="mt-5 flex gap-3"><button disabled={busy==="result"} className="rounded-xl bg-indigo-600 px-5 py-3 font-black text-white">Save result</button><button type="button" onClick={()=>setSelectedCall(null)} className="font-bold text-slate-500">Cancel</button></div></form></div>}
  </div></main>;
}
